services:
  web:
    image: python:3.8-slim
    build:
      context: .
    commands:
      start: gunicorn app:app
    ports:
      - 5000
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

  worker:
    image: python:3.8-slim
    build:
      context: .
    commands:
      start: python3 video_consumer.py
